App\DispenserContext\Domain\Entity\Dispenser:
  attributes:
    normalization_context:
      groups: ['read']
  collectionOperations:
      create:
        method: POST
        path: /dispensers/create
        controller: App\DispenserContext\Infrastructure\Api\Action\Dispenser\Create
        denormalization_context:
          groups: ['write']
        openapi_context:
          summary: Create a new dispenser
      summary:
        method: 'GET'
        path: '/dispensers'
  itemOperations:
      get:
        method: GET