App\Entity\Sale:
  attributes:
    normalization_context:
      groups: ['read']
  collectionOperations:
      summary:
        method: 'GET'
        path: '/sales'
  itemOperations:
      get:
        method: GET