App\DispenserContext\Domain\Entity\User:
  attributes:
    normalization_context:
      groups: ['user_read']
  collectionOperations:
    register:
      method: POST
      path: /users/register
      controller: App\DispenserContext\Infrastructure\Api\Action\User\Register
      denormalization_context:
        groups: ['user_write']
      openapi_context:
        summary: Register a new user
  itemOperations:
    get:
      method: GET