App\DispenserContext\Domain\Entity\Dispenser:
  attributes:
    id:
      groups: ['read']
    dispenserFlowVolume: 
      groups: ['read', 'write']
    dispenserAmount:
      groups: ['read', 'write']
    dispenserStatus:
      groups: ['read']
    createdAt:
      groups: ['read']
    updatedAt:
      groups: ['read']