App\Entity\Sale:
  attributes:
    saleId:
      groups: ['read']
    dispenserId: 
      groups: ['read']
    litersSold:
      groups: ['read']
    secondsUsed:
      groups: ['read']
    createdAt:
      groups: ['read']