App\DispenserContext\Domain\Entity\Sale:
  attributes:
    id:
      groups: ['read']
    dispenserId: 
      groups: ['read']
    litersSold:
      groups: ['read']
    secondsUsed:
      groups: ['read']
    createdAt:
      groups: ['read']