App\Entity\User:
  attributes:
    id:
      groups: ['user_read']
    name:
      groups: ['user_read', 'user_write']
    email:
      groups: ['user_read', 'user_write']
    password:
      groups: ['user_write']
    active:
      groups: ['user_read']
    createdAt:
      groups: ['user_read']
    updatedAt:
      groups: ['user_read']